[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
name = "shared"
path = "src/lib.rs"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
tokio = { version = "1.41.1", features = ["full"] }
